from .user import User
from .tags import Tags
from .genres import Genres
from .pages import Pages
from .comments import Comments
from .favourites import Favourites
from .comics import Comics
from .chapters import Chapters
from .tag_comics import Tag_comics
from .genres_comics import Genres_comicses
